

rag.location.txt=src/main/resources/rag/txt
rag.location.csv=src/main/resources/rag/csv
rag.location.pdf=src/main/resources/rag/pdf

###REDIS###
redis.hosts=redis://localhost:6379
redis.type=standalone
quarkus.redis.hosts=${redis.hosts}
quarkus.redis.client-type=${redis.type}
quarkus.redis.max-pool-size=20
quarkus.redis.max-pool-waiting=100


####OLLAMA####
#quarkus.langchain4j.chat-model.provider=ollama
#quarkus.langchain4j.embedding-model.provider=ollama
#quarkus.langchain4j.ollama.embedding-model.model-id=mxbai-embed-large
#quarkus.langchain4j.redis.dimension=1024
#quarkus.langchain4j.ollama.timeout=60


####OPENAI####
quarkus.langchain4j.openai.api-key= ###
quarkus.langchain4j.chat-model.provider=openai
quarkus.langchain4j.embedding-model.provider=openai
quarkus.langchain4j.openai.chat-model.model-name=gpt-4
quarkus.langchain4j.redis.dimension=1536
quarkus.langchain4j.openai.embedding-model.model-name=text-embedding-ada-002

####DEEPSEEK####

####MISTRAL####
